apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwi-web
  template:
    metadata:
      labels:
        app: kiwi-web
    spec:
      containers:
      - name: kiwi-web
        image: kiwitcms/kiwi:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        env:
        - name: KIWI_DB_ENGINE
          value: "django.db.backends.postgresql"
        - name: KIWI_DB_HOST
          value: "kiwi-db-service"
        - name: KIWI_DB_PORT
          value: "5432"
        - name: KIWI_DB_NAME
          value: "kiwi"
        - name: KIWI_DB_USER
          value: "kiwi"
        - name: KIWI_DB_PASSWORD
          value: "kiwi"
        securityContext:
          capabilities:
            drop:
              - ALL
        volumeMounts:
            - mountPath: /Kiwi/uploads
              name: uploads

      volumes:
      - name: uploads
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: kiwi-web-service
spec:
  selector:
    app: kiwi-web
  ports:
  - name: kiwi1
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: kiwi2
    protocol: TCP
    port: 443
    targetPort: 8443

---

apiVersion: v1
kind: Service
metadata:
  name: kiwi-web-service-nodeport
spec:
  type: NodePort  # 將服務類型改為 NodePort
  selector:
    app: kiwi-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001  # 選擇一個合適的 NodePort 編號
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwi-db
  template:
    metadata:
      labels:
        app: kiwi-db
    spec:
      containers:
      - name: kiwi-db
        image: postgres:latest
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
        env:
        - name: POSTGRES_DB
          value: "kiwi"
        - name: POSTGRES_USER
          value: "kiwi"
        - name: POSTGRES_PASSWORD
          value: "kiwi"
      volumes:
      - name: db-data
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: kiwi-db-service
spec:
  selector:
    app: kiwi-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

